package com.compilador.semantic;

import com.compilador.model.ASTNode;
import com.compilador.model.SymbolTable;
import com.compilador.model.Token;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.*;

@Component
public class SemanticAnalyzer {

    private final DataSource dataSource;
    private SymbolTable symbolTable;

    public SemanticAnalyzer(DataSource dataSource) {
        this.dataSource = dataSource;
        this.symbolTable = new SymbolTable();
        loadMetadata();
    }

    private void initDatabase() {
        try (Connection conn = dataSource.getConnection()) {
            var stmt = conn.createStatement();

            stmt.execute("CREATE TABLE IF NOT EXISTS usuarios ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " nombre VARCHAR(100) NOT NULL,"
                    + " edad INT NOT NULL,"
                    + " email VARCHAR(100),"
                    + " ciudad VARCHAR(100))");
            stmt.execute("CREATE TABLE IF NOT EXISTS productos ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " nombre VARCHAR(100) NOT NULL,"
                    + " precio DOUBLE PRECISION NOT NULL,"
                    + " stock INT NOT NULL,"
                    + " categoria VARCHAR(100))");
            stmt.execute("CREATE TABLE IF NOT EXISTS pedidos ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " usuario_id INT NOT NULL,"
                    + " producto_id INT NOT NULL,"
                    + " cantidad INT NOT NULL,"
                    + " fecha VARCHAR(20))");

            stmt.execute("CREATE TABLE IF NOT EXISTS tablas ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " nombre VARCHAR(100) UNIQUE NOT NULL)");
            stmt.execute("CREATE TABLE IF NOT EXISTS columnas ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " tabla_id INT REFERENCES tablas(id) ON DELETE CASCADE,"
                    + " nombre VARCHAR(100) NOT NULL,"
                    + " tipo VARCHAR(50) DEFAULT 'VARCHAR',"
                    + " UNIQUE(tabla_id, nombre))");

            var rs = stmt.executeQuery("SELECT COUNT(*) FROM tablas");
            rs.next();
            if (rs.getInt(1) == 0) {
                seedData(conn);
            }
        } catch (Exception e) {
            System.err.println("[Semántico] DB init error: " + e.getMessage());
        }
    }

    private void seedData(Connection conn) throws Exception {
        var stmt = conn.createStatement();

        stmt.execute("INSERT INTO tablas (nombre) VALUES ('usuarios')");
        stmt.execute("INSERT INTO tablas (nombre) VALUES ('productos')");
        stmt.execute("INSERT INTO tablas (nombre) VALUES ('pedidos')");

        stmt.execute("INSERT INTO columnas (tabla_id, nombre, tipo) SELECT t.id, c.n, c.t FROM tablas t, "
                + "(VALUES ('id','INTEGER'),('nombre','VARCHAR'),('edad','INTEGER'),('email','VARCHAR'),('ciudad','VARCHAR'))"
                + " AS c(n,t) WHERE t.nombre='usuarios' AND NOT EXISTS (SELECT 1 FROM columnas WHERE tabla_id=t.id)");
        stmt.execute("INSERT INTO columnas (tabla_id, nombre, tipo) SELECT t.id, c.n, c.t FROM tablas t, "
                + "(VALUES ('id','INTEGER'),('nombre','VARCHAR'),('precio','DOUBLE'),('stock','INTEGER'),('categoria','VARCHAR'))"
                + " AS c(n,t) WHERE t.nombre='productos' AND NOT EXISTS (SELECT 1 FROM columnas WHERE tabla_id=t.id)");
        stmt.execute("INSERT INTO columnas (tabla_id, nombre, tipo) SELECT t.id, c.n, c.t FROM tablas t, "
                + "(VALUES ('id','INTEGER'),('usuario_id','INTEGER'),('producto_id','INTEGER'),('cantidad','INTEGER'),('fecha','VARCHAR'))"
                + " AS c(n,t) WHERE t.nombre='pedidos' AND NOT EXISTS (SELECT 1 FROM columnas WHERE tabla_id=t.id)");

        stmt.execute("INSERT INTO usuarios (nombre, edad, email, ciudad) VALUES "
                + "('Ana Garcia', 25, 'ana@email.com', 'Madrid'),"
                + "('Carlos Lopez', 32, 'carlos@email.com', 'Barcelona'),"
                + "('Maria Rodriguez', 17, 'maria@email.com', 'Valencia')");
        stmt.execute("INSERT INTO productos (nombre, precio, stock, categoria) VALUES "
                + "('Laptop', 1200.50, 15, 'Electronica'),"
                + "('Mouse', 25.99, 100, 'Accesorios')");
        stmt.execute("INSERT INTO pedidos (usuario_id, producto_id, cantidad, fecha) VALUES "
                + "(1, 1, 2, '2024-01-15'),"
                + "(2, 2, 5, '2024-01-20')");

        System.out.println("[Semántico] Seed data inserted successfully");
    }

    private void loadMetadata() {
        initDatabase();
        try (Connection conn = dataSource.getConnection()) {
            var stmt = conn.prepareStatement("""
                SELECT t.nombre as tabla, c.nombre as columna, c.tipo
                FROM tablas t
                JOIN columnas c ON t.id = c.tabla_id
                ORDER BY t.nombre, c.nombre
            """);
            ResultSet rs = stmt.executeQuery();

            Map<String, List<SymbolTable.ColumnaInfo>> map = new HashMap<>();
            while (rs.next()) {
                String tabla = rs.getString("tabla").toLowerCase();
                String columna = rs.getString("columna");
                String tipo = rs.getString("tipo");
                map.computeIfAbsent(tabla, k -> new ArrayList<>())
                        .add(new SymbolTable.ColumnaInfo(columna, tipo));
            }

            map.forEach((tabla, cols) -> {
                symbolTable.agregarTabla(tabla, cols);
                System.out.println("[Semántico] Cargada tabla '" + tabla + "' con " + cols.size() + " columnas");
            });
            System.out.println("[Semántico] Metadata cargada: " + map.size() + " tablas");

        } catch (Exception e) {
            System.err.println("[Semántico] Error cargando metadata: " + e.getMessage());
        }
    }

    public SemanticResult validate(ASTNode ast, List<Token> tokens) {
        long start = System.nanoTime();
        List<String> errors = new ArrayList<>();
        Map<String, Object> symTableInfo = new LinkedHashMap<>();

        if (ast == null) {
            return new SemanticResult(false, List.of("AST nulo"), symTableInfo, 0);
        }

        String tipo = ast.getTipo();
        String tabla = extractTableName(ast);
        List<String> columnas = extractColumnNames(ast);

        symTableInfo.put("tipo_consulta", tipo);
        symTableInfo.put("tabla", tabla != null ? tabla : "N/A");

        if (tabla != null && !symbolTable.existeTabla(tabla)) {
            String msg = "Error Semántico: La tabla '" + tabla + "' no existe en la base de datos";
            errors.add(msg);
            System.err.println("[Semántico] " + msg);
        } else if (tabla != null && "SELECCIONAR".equals(tipo)) {
            List<String> invalidColumns = new ArrayList<>();
            for (String col : columnas) {
                if (!col.equals("*") && !symbolTable.existeColumna(tabla, col)) {
                    invalidColumns.add(col);
                }
            }
            if (!invalidColumns.isEmpty()) {
                String msg = "Error Semántico: La(s) columna(s) " + invalidColumns
                        + " no existe(n) en la tabla '" + tabla + "'";
                errors.add(msg);
                System.err.println("[Semántico] " + msg);
            }
        }

        // Validate INSERT columns if present
        if ("INSERTAR".equals(tipo)) {
            // For INSERT, values are positional, so we validate count matches
            List<ASTNode> values = findNodes(ast, "VALORES");
            symTableInfo.put("valores_count", values.size());
        }

        // Validate UPDATE columns in assignments
        if ("MODIFICAR".equals(tipo) && tabla != null) {
            List<ASTNode> assigns = findNodes(ast, "ASIGNACIONES");
            for (ASTNode assign : assigns) {
                if (assign.getHijos().size() >= 1) {
                    String colName = assign.getHijos().get(0).getValor();
                    if (!symbolTable.existeColumna(tabla, colName)) {
                        String msg = "Error Semántico: La columna '" + colName
                                + "' no existe en la tabla '" + tabla + "'";
                        errors.add(msg);
                        System.err.println("[Semántico] " + msg);
                    }
                }
            }
        }

        symTableInfo.put("tablas_disponibles", symbolTable.getTablasDisponibles());
        symTableInfo.put("columnas_disponibles",
                tabla != null && symbolTable.existeTabla(tabla)
                        ? symbolTable.getColumnas(tabla).stream().map(SymbolTable.ColumnaInfo::getNombre).toList()
                        : List.of());

        long elapsed = (System.nanoTime() - start) / 1_000_000;

        return new SemanticResult(errors.isEmpty(), errors, symTableInfo, elapsed);
    }

    private String extractTableName(ASTNode node) {
        for (ASTNode child : node.getHijos()) {
            if ("TABLA".equals(child.getTipo())) {
                return child.getValor().toLowerCase();
            }
        }
        return null;
    }

    private List<String> extractColumnNames(ASTNode node) {
        for (ASTNode child : node.getHijos()) {
            if ("COLUMNAS".equals(child.getTipo())) {
                return child.getHijos().stream()
                        .map(ASTNode::getValor)
                        .filter(v -> !v.equals(","))
                        .toList();
            }
        }
        return List.of();
    }

    private List<ASTNode> findNodes(ASTNode node, String tipo) {
        List<ASTNode> result = new ArrayList<>();
        if (node.getTipo().equals(tipo)) {
            result.add(node);
        }
        for (ASTNode child : node.getHijos()) {
            result.addAll(findNodes(child, tipo));
        }
        return result;
    }

    public SymbolTable getSymbolTable() {
        return symbolTable;
    }

    public record SemanticResult(boolean valido, List<String> errores, Map<String, Object> simbolos, long tiempoMs) {}
}
