server.port=8083
spring.application.name=semantico-service

spring.datasource.url=jdbc:postgresql://compilador-db:5432/compilador
spring.datasource.username=compilador
spring.datasource.password=compilador123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never
