server.port=8080
spring.application.name=orchestrator

spring.datasource.url=jdbc:postgresql://compilador-db:5432/compilador
spring.datasource.username=compilador
spring.datasource.password=compilador123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never

lexico.url=http://lexico-service:8081
sintactico.url=http://sintactico-service:8082
semantico.url=http://semantico-service:8083
